IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USUARIO')
BEGIN
    CREATE TABLE USUARIO(
    ID_USUARIO INT IDENTITY NOT NULL,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    LOGIN VARCHAR(20) NOT NULL,
	CHAVE_ACESSO VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	INDICA_PACIENTE BIT NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    );
END	